### ISSUE TITLE
Documentation: add the ability to jump into different sections

### ISSUE THREAD

**Issue by claucece** [open-quantum-safe/liboqs#1020]
In the html generated documentation, the links to different sections on the same page don't work.
It seems to be possible to do this though, by using something like: http://doxygen.10944.n7.nabble.com/Creating-links-in-and-between-Markdown-files-pages-td6689.html

Though, this might break the markdown links...

**Comment by dstebila** [comment]
Thanks Sofía.  Are you referring to the Markdown files that (e.g., README.md) that are pulled in to Doxygen during the Doxygen generation process?  I am wondering if the method in the link (using `@ref ...`) you provided is pure Markdown or if it's Doxygen-specific.  If it's Doxygen-specific, I'd be hesitant to use it, as I'd want our Markdown files to be valid as Markdown files, and especially that they display well on Github, since that's the form that most people will use them in, I think.

**Comment by claucece** [comment]
I agree.I think this is doxygen-specific. I'll try searching if there is a solution for both worlds ;)

**Comment by dstebila** [comment]
Anything further on this? Otherwise will close as won't-fix.

**Comment by claucece** [comment]
I didn't find a way so far of doing it: it is either the html or markdown. So, I think it is good to close.
