### ISSUE TITLE
Deal with CI backlog

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1025]
@xvzcf You had some concerns about backlog of incomplete coverage in CI, e.g. some algorithms being disabled on AppVeyor.  Can you document those in this issue?

**Comment by xvzcf** [comment]
Yes, was going to do so later today.

**Comment by xvzcf** [comment]
We might want to go over these before adding new CI jobs:

- [appveyor_build.bat](https://github.com/open-quantum-safe/liboqs/blob/main/appveyor_build.bat#L10): SPHINCS and Rainbow are disabled
- [.circleci/config.yml](https://github.com/open-quantum-safe/liboqs/blob/main/.circleci/config.yml#L344): There are several disabled jobs
- A commit to `main` triggers various downstream sub-project jobs, and our CircleCI plan has a limit of 1 concurrent job
- This triggering mechanism currently only applies to CircleCI jobs, and not to Appveyor or GitHub Actions ones
- OpenSSL and OpenSSH (possibly others) CI jobs don't test the full suite of algorithms because only a subset is enabled by default (this generally hasn't caused us too many problems)
- Our plan allows "1 concurrent job with access to Linux and Windows builds on Small and Medium sizes", and it would be nice to consolidate CI systems (subject to all the considerations stemming from the previous points)

I also noticed [here](https://app.circleci.com/pipelines/github/open-quantum-safe/liboqs/1554/workflows/21c8fdf0-1572-47dd-bd8c-d88dbcb95998/jobs/14491) that the triggering mechanism doesn't fail if the branch wasn't found. I introduced this bug, will fix it.

**Comment by baentsch** [comment]
If I get it right, every single item above was triggered by the need to save (CI) time, either because the algorithms are too slow (i.e., we effectively did pick (on :) "losers") or the tests are too time-consuming/not adding serious value (to warrant their regular execution).

So I see some alternatives for resolution:
1) We buy more CCI resources (for parallel execution).
2) We create a more convoluted "tier system" of tests (PR run, audit-run, release-run, etc.) with different levels of "thoroughness" (i.e., time/resource demands)
3) We "mix" testing options, i.e., not doing full matrix tests, but do testing of specific features/algorithms only on specific setups (say, Rainbow only on shared x86 builds and Sphincs only on static arm builds). Absolutely non-ideal but may allow us to test more within the given CI resource budget.
4) We switch to a completely different CI mechanism, e.g., one permitting addition of "self"-maintained executors: We might then use machines (and architectures) we chose (also adding IBM ("donated" :) mainframes for `s390`, IBM Power machines for `ppc64le`, AWS cloud for mainstream `x64` or `arm64`). But that'd be a major undertaking.....

I intentionally didn't list the fifth option to _add_ another CI system (for on-demand or release-only testing): It would make our system even harder to maintain/remain consistent.

Further ideas very welcome.

**Comment by xvzcf** [comment]
> If I get it right, every single item above was triggered by the need to save (CI) time, either because the algorithms are too slow (i.e., we effectively did pick (on :) "losers") or the tests are too time-consuming/not adding serious value (to warrant their regular execution).

Agreed, and the need to save CI time is still present.

I also think the easiest way out would be to buy more CircleCI resources, but we can discuss this on Wednesday.

**Comment by dstebila** [comment]
Basically resolved, with the exception of a few jobs; closing this issue and tracking the remaining jobs separately in #1076.
