### ISSUE TITLE
Execution failures with picnic on M1 when using gcc-11

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1178]
Continuation of #1164 (just for picnic)

**Comment by dstebila** [comment]
@sebastinas, in a [PR for a separate issue related to building with gcc-11 on Apple M1](https://github.com/open-quantum-safe/liboqs/pull/1177), we noticed that the [known answer tests for Picnic were failing](https://github.com/open-quantum-safe/liboqs/pull/1177/checks?check_run_id=4863789372).  @Martyrshot checked if the bug was introduced in that PR or whether it was present in main prior to that PR, and it turns out it was present in main prior to that PR.  So we must have missed it in the testing for #1167 (we didn't have full continuous integration on M1 set up by then, but now we do).  Any ideas what might be happening?  If you need access to an M1 machine, I can give you an account.

**Comment by sebastinas** [comment]
An account on an M1 would help. I am only able to test ARM64 in qemu otherwise, where I haven't seen any issues with the KATs.

**Comment by dstebila** [comment]
> An account on an M1 would help. I am only able to test ARM64 in qemu otherwise, where I haven't seen any issues with the KATs.

Sure, let's coordinate over email.  Can you send me an email with an SSH public key?

**Comment by sebastinas** [comment]
Done, sent my SSH public key per mail.
