### ISSUE TITLE
Constant time checks for Kyber on AVX2 failing

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1187]
This was picked up by the weekly builds: https://github.com/open-quantum-safe/liboqs/runs/5080898885?check_suite_focus=true#step:6:339

Not sure what changed -- no changes to the Kyber Intel code in a few months, as far as I can tell.

**Comment by dstebila** [comment]
I re-ran locally on a machine with AVX2 and wasn't able to reproduce -- the tests all passed.  I've triggered the job to re-run on Github Actions, we'll see if it recurs.

**Comment by bhess** [comment]
I was able to reproduce it, but it only occurs after a few runs. The reason seems to be because the AVX2 version of Kyber uses both an AVX2 version and a non-AVX2 version for rejection sampling (rej_uniform). The non-AVX2 version is only used if more samples are needed.

A suppression rule for the non-AVX2 version of rej_uniform is currently missing and would need to be added.
