### ISSUE TITLE
Update Kyber and Dilithium ARM code.

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/liboqs#1320]

**Comment by xvzcf** [comment]
As previously noted, our implementations are from PQClean, which in turn takes it from the [neon-ntt](https://github.com/neon-ntt/neon-ntt) project.

**Comment by baentsch** [comment]
> As previously noted, our implementations are from PQClean, which in turn takes it from the [neon-ntt](https://github.com/neon-ntt/neon-ntt) project.

Interesting to note -- what's the implication of this for us? Did PQClean not integrate the latest code from neon-ntt yet? Is neon-ntt itself not up-to-date compared to the ref implementation?

**Comment by dstebila** [comment]
PQClean doesn't have the latest code from neon-ntt.

**Comment by baentsch** [comment]
> PQClean doesn't have the latest code from neon-ntt.

Is this still the case? Or would/should a fresh `copy_from_upstream` resolving #1506 also resolve this issue?

**Comment by mczraf** [comment]
> > PQClean doesn't have the latest code from neon-ntt.
> 
> Is this still the case? Or would/should a fresh `copy_from_upstream` resolving #1506 also resolve this issue?

I believe it is still the case. I've checked [PQClean repo](https://github.com/PQClean/PQClean/commits/master/crypto_kem/kyber768/aarch64/neon_poly.c), and they are still using the original Neon implementation from Sep/2021.  

It might be worth adding that upgrading this implementation to a newer version may lead to some additional benefits. For example, LibOQS Kyber's implementation is not marked as passing all Valgrind branch-on-secrets tests ([see here](https://github.com/open-quantum-safe/liboqs/blob/main/docs/algorithms/kem/kyber.md)). There's a chance this could be automatically fixed by simply resorting to the newer Neon implementation. PS: At the moment, I can't dedicate cycles to this effort myself unfortunately but I thought it would be helpful to comment here to reinforce that this seems like an interesting move for LibOQS. 

Thank you all for this amazing project :)

Rafael Misoczki (speaking for myself)

**Comment by baentsch** [comment]
Thanks for the feedback, @mczraf ! https://github.com/PQClean/PQClean/pull/493 seems to confirm --and be work to resolve-- this.

**Comment by SWilson4** [comment]
Fixed by #1512.
