### ISSUE TITLE
doxygen > 1.9.2 failing

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1332]
Starting with doxygen 1.9.3, header section links in CONFIGURE.md cannot be processed any more, e.g., 
```
CONFIGURE.md:5: error: unable to resolve reference to 'BUILD_SHARED_LIBS' for \ref command
```
Weird thing: The same referencing doesn't trigger errors in README.md. Adding explicit `{#LABELNAME}` references as per https://www.doxygen.nl/manual/markdown.html#md_links eliminates the error, but then creates "unsightly" github markdown artifacts: 
![grafik](https://user-images.githubusercontent.com/57787676/207564870-f6513dd4-62a8-4efc-b46e-709afa2d7aca.png)

Edit/Add: In contrast to local run, in CI, README.md fails, too (without explicit link labels).

Ideas how to fix welcome (@xvzcf ?). This is the cause for the "main" branch build error.

**Comment by xvzcf** [comment]
Doxygen 1.9.5 also reports errors for `@param` commands documenting arguments to function pointers, such as in [kem.h](https://github.com/open-quantum-safe/liboqs/blob/main/src/kem/kem.h#L175) for example. The issue has been reported [here](https://github.com/doxygen/doxygen/issues/9552) and is still open. 

In addition, I believe the result [here](https://github.com/open-quantum-safe/ci-containers/pull/61#issuecomment-1336350517) was a success because we do not check the return code of the commands in [scripts/run_doxygen.sh](https://github.com/open-quantum-safe/liboqs/blob/main/scripts/run_doxygen.sh). Adding `set -o errexit` would be nice, but then we'd actually have to fix the issues that come up ...

**Comment by dstebila** [comment]
I checked the web server usage logs and there are a few non-bot hits a day on the API documentation generated from Doxygen.  So it would be nice to keep that around still.  But we could remove all the Markdown files from the set of things processed by Doxygen, would that solve the problem?

**Comment by baentsch** [comment]
> would that solve the problem?

I think so, yes.
