### ISSUE TITLE
Decide and document default config values

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1356]
https://github.com/open-quantum-safe/liboqs/wiki/Customizing-liboqs doesn't document in all cases the default values. This issue is to trigger discussion and documentation on those:

Strawman proposal:
- BUILD_SHARED_LIBS: OFF - documented OK.
- CMAKE_BUILD_TYPE: undefined/documented default. Proposal "Release"
- OQS_ENABLE_KEM/SIG: ON by default - documented OK
- OQS_BUILD_ONLY_LIB: undefined/-documented default. Proposal "OFF"
- OQS_MINIMAL_BUILD: unset by default - documented OK
- OQS_DIST_BUILD: undefined/-documented default. Proposal: "ON" (change from today's apparent default "OFF")
- OQS_USE_OPENSSL: ON by default - documented OK
- OQS_SPEED_USE_ARM_PMU: undefined/-documented default. Proposal: "ON"
- USE_SANITIZER: undefined/-documented default. Proposal "Undefined"
- OQS_ENABLE_TEST_CONSTANT_TIME: undefined/-documented default. Proposal "ON"

**Comment by dstebila** [comment]
Thanks Michael, this is a good improvement.  I agree with the proposed defaults on all of them except USE\_SANITIZER -- I don't think there should be a default sanitizer enabled, because most builds would not be built for sanitizer checking.  The change for OQS\_DIST\_BUILD is particularly good considering the recent liboqs-go issue, as I was reviewing the PR there I thought that perhaps we should change to make builds distributable by default.

**Comment by baentsch** [comment]
> I don't think there should be a default sanitizer enabled

Good for me. But then we shall document that.

>  The change for OQS_DIST_BUILD is particularly good considering the recent liboqs-go issue

That also triggered this for me. But this might bring https://github.com/open-quantum-safe/liboqs/issues/1264 to the fore... But then again, we don't have CI for that OS/HW combination. So will do a PR before updating the Wiki.

The last statement makes me wonder: Why do we keep this information only in a Wiki and don't put it in a file (that would then be contained in a distribution)? I think I'll change that as part of the PR unless there's voices to the opposite.
