### ISSUE TITLE
About security audit

### ISSUE THREAD

**Issue by VegeBun-csj** [open-quantum-safe/liboqs#1364]
Has this library considered standardization? such as very mature libraries such as rsa or aes. Or is there any plan to submit it to a special audit company for audit, and finally become a standard. Post-quantum signature/encryption algorithms need such libraries very much.

**Comment by evil-user** [comment]
@VegeBun-csj are you planning to do security audit of liboqs or sponsor a security audit ?  I think it would be a great way to contribute to this project , As far as i know liboqs devs have clearly mentioned in liboqs limitations and security "WE DO NOT CURRENTLY RECOMMEND RELYING ON THIS LIBRARY IN A PRODUCTION ENVIRONMENT OR TO PROTECT ANY SENSITIVE DATA. This library is meant to help with research and prototyping. While we make a best-effort approach to avoid security bugs, this library has not received the level of auditing and analysis that would be necessary to rely on it for high security use.", since most algorithms are in research stage it is highly unlikely that liboqs dev team would even consider an security audit in near future until post quantum algorithms become stable enough.

**Comment by dstebila** [comment]
Regarding "standardization": libraries aren't standardized, algorithms are.  Once final standards emerge for the algorithms in liboqs, we will use those standards.  It is possible to have cryptographic libraries certified against standards (e.g., FIPS validation); we don't have plans for that at this point.

Regarding auditing: we haven't had liboqs audited, and there isn't too much point in doing so while the algorithm specifications are not finalized.  It's something we'll keep in mind for later.
