### ISSUE TITLE
0.8.0rc1 MSVC 32-bit builds fail on Falcon with AVX

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1488]
### Discussed in https://github.com/orgs/open-quantum-safe/discussions/1487

<div type='discussions-op-text'>

<sup>Originally posted by **blackbird1999** May 31, 2023</sup>
 44>D:\CDK8.1\liboqs\src\sig\falcon\pqclean_falcon-512_avx2\sign.c(1033): error C2440: 'function': cannot convert fr
       om 'int' to '__m128i' [D:\CDK8.1\liboqs\buildmt\src\sig\falcon\falcon_512_avx2.vcxproj]
    41>D:\CDK8.1\liboqs\src\sig\falcon\pqclean_falcon-1024_avx2\sign.c(1033): error C2440: 'function': cannot convert f
       rom 'int' to '__m128i' [D:\CDK8.1\liboqs\buildmt\src\sig\falcon\falcon_1024_avx2.vcxproj]

It appears that the AVX2 code no longer matches that found here https://falcon-sign.info/falcon-round3.zip. In particular, it no longer has the #ifdef for x64/x86 that allows it to compile. 

I'm not sure of the steps to report such things. Thanks for your help!

Sincerely,
Jonathan
</div>

**Comment by dstebila** [comment]
Should be fixed by pulling in https://github.com/PQClean/PQClean/pull/492 once it lands.

**Comment by baentsch** [comment]
Would it be sensible to add this as a known issue to the 0.8.0 release notes in github (not those in the release itself, of course)? And add this to the next milestone? 0.8.1 or 0.9.0, btw?

**Comment by dstebila** [comment]
Okay, I've added a note to the release notes on Github.

**Comment by baentsch** [comment]
> Should be fixed by pulling in [PQClean/PQClean#492](https://github.com/PQClean/PQClean/pull/492) once it lands.

Hmm -- that PR fails CI and doesn't look like it's moving since more than a month now.

So what about two more options to get this cleared for the 0.9.0 milestone:
1) Document Falcon on 32bit MSVC platforms (Windows x86?) as unsupported (as it apparently should be considering the "prohibition" for platform-specific defines in PQClean if I understand this right).
2) Pull from Falcon's upstream and not from PQClean

Anyone with more knowledge about the complications of directly importing Falcon from its origin may comment on option 2. But option 1 seems to be very attractive -- at least as a stopgap to move towards our next release: 32 bit MSVC builds don't look like an awfully big use base; [other `liboqs` algorithms don't work on Windows at all](https://github.com/open-quantum-safe/liboqs/pull/1509)). And for the very few users doing that, well, they may (and apparently already do) use the original upstream code directly (if neither option 2 nor the PQClean PR moves), correct @blackbird1999?

**Comment by blackbird1999** [comment]
At this point, I'd say Falcon not working is a bigger deal than BIKE as one is on a standardization path, and one isn't. However, since OQS states its purpose is "These tools support [research](https://openquantumsafe.org/research) by ourselves and others." I can't really argue that this matters unless I want to argue that OQS has moved beyond its original purpose.

Yes, it's trivial for me to merge in the original Falcon code and this can be put off by documenting it as unsupported.

**Comment by baentsch** [comment]
Thanks for that perspective, @blackbird1999 . Do you have a need for further algorithms beyond Falcon? If so, it'd be beneficial for both of us to resolve this for good (i.e., pull upstream code into liboqs so you have one API to deal with and liboqs to have the latest code). If not, option 2 indeed sounds like a "quick resolution" not hurting anybody.

**Comment by blackbird1999** [comment]
Yes, we're using all the selected for standardization algorithms. I just patched the liboqs falcon AVX files after download so it's still just one API. I'm not pulling down the Falcon sources and using them separately. liboqs's API is too nice for me to want to do that :)

**Comment by baentsch** [comment]
> we're using all the selected for standardization algorithms.

That's _the_ argument against option 1 above. A non-option now.

> I just patched the liboqs falcon AVX files after download so it's still just one API.

That's indeed a forth option for us, too: Thanks for bringing that up! We have a built-in patch mechanism for "copy_from_upstream". @dstebila : What's your take (as to what's easier/quicker): Do such "rever-to-upstream" patch in `liboqs` or get https://github.com/PQClean/PQClean/pull/492 integrated and pull that?

**Comment by dstebila** [comment]
> > Should be fixed by pulling in [PQClean/PQClean#492](https://github.com/PQClean/PQClean/pull/492) once it lands.
> 
> Hmm -- that PR fails CI and doesn't look like it's moving since more than a month now.

I haven't had a chance to get back to it to try to resolve the outstanding failures.  I don't think there's anything fundamental, it just requires iterating through various tweaks to get the slow builds to pass.

>     2. Pull from Falcon's upstream and not from PQClean

Falcon's upstream is no longer up to date with respect to the "current" version of Falcon; as far as I know PQClean has the only public implementation of the current version of Falcon.

**Comment by dstebila** [comment]
> > I just patched the liboqs falcon AVX files after download so it's still just one API.
> 
> That's indeed a forth option for us, too: Thanks for bringing that up! We have a built-in patch mechanism for "copy_from_upstream". @dstebila : What's your take (as to what's easier/quicker): Do such "rever-to-upstream" patch in `liboqs` or get [PQClean/PQClean#492](https://github.com/PQClean/PQClean/pull/492) integrated and pull that?

If it is possible to get the PQClean problems resolved that it less brittle, I think.

**Comment by dstebila** [comment]
FYI @bhess this is not fixed by #1512 since #1512 pulls from https://github.com/PQClean/PQClean/commit/66e50172055aaf1b9a16d8f35fe03b0807f2723e but the Falcon changes landed in https://github.com/PQClean/PQClean/commit/c3abebf4ab1ff516ffa71e6337f06d898952c299.  We can save fixing this until after you've got #1512 sorted, don't want to complicate #1512 unnecessarily.
