### ISSUE TITLE
pytest 7.4: --numprocesses=auto not recognized

### ISSUE THREAD

**Issue by c-93** [open-quantum-safe/liboqs#1580]
**Describe the bug**
At least pytest-7.2.2 and pytest-7.4.2 fail for me with the following error:

```
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --numprocesses=auto
  inifile: None
  rootdir: <root_dir>
```

**To Reproduce**
1. Build the project, and execute `ninja run_tests` with the mentioned pytest versions.

**Expected behavior**
Test execution starts. (no error)

**Environment (please complete the following information):**
 - OS: Fedora 37
 - liboqs main branch
 - pytest-7.2.2 or pytest-7.4.2

**Workaround**
Remove `--numprocesses=auto` from /liboqs/tests/CMakeLists.txt    
As removing this option seems to increase compatibility, I suggest this to be the default (or to replace it with a similar option).

**Comment by baentsch** [comment]
> __main__.py: error: unrecognized arguments: --numprocesses=auto

This error occurs if `pytest-xdist` is not installed. However, this package is clearly listed [as prerequisite in documentation](https://github.com/open-quantum-safe/liboqs#linuxmacos).

> As removing this option seems to increase compatibility, I suggest this to be the default (or to replace it with a similar option).

Without this feature of "pytest-xdist" testing takes way too long -- and is way too inefficient on standard multicore processors. If you know of an alternative (command line option) to bring testing to the same performance level, please let us know. Otherwise we'll have to close this issue as "documented"/don't fix.

**Comment by c-93** [comment]
You are correct. I apologize for my misunderstanding. Thanks for the extra explanation.

**Comment by c-93** [comment]
"documented"/don't fix
