### ISSUE TITLE
Improve AppVeyor configuration

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#160]
@vsoftco what changes did you want to make?  I remember something about the non-debug build, making it go faster, ...

**Comment by christianpaquin** [comment]
I've enabled signatures in the Windows build (PR #169), but Picnic is disabled by default due to its Linux-generated dependencies (needed to generate the parameters). @vsoftco, can we store static files in AppVeyor? If so, we could store the Picnic params there, and enable the scheme by default. If not, can we run a Linux script before running the Windows build/test?
