### ISSUE TITLE
Windows build with "-DBUILD_SHARED_LIBS=ON"

### ISSUE THREAD

**Issue by smcmahonibm** [open-quantum-safe/liboqs#1749]
**Describe the bug**
Building on Windows with shared lib (.dll) setting "-DBUILD_SHARED_LIBS=ON" fails to build kat_kem and kat_sig.
Either ninja or MSBuild or MSVC project files all get same error.

**To Reproduce**
clone liboqs main branch
> mkdir build
> cd build
> cmake -GNinja -DBUILD_SHARED_LIBS=ON ..
> ninja
...
... fails to link kat_kem.exe and kat_sig.exe
(see screenshot below)

**Expected behavior**
kat_kem.exe and kat_sig.exe should build OK.
The oqs.dll and all other .exe build OK.
Those test build OK with static lib only build - i.e. no "-DBUILD_SHARED_LIBS=ON".

**Screenshots**
ninja console output:
```
[659/671] Linking C executable tests\kat_kem.exe
FAILED: tests/kat_kem.exe
cmd.exe /C "cd . && "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=tests\CMakeFiles\kat_kem.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\PROFES~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x64\link.exe /nologo tests\CMakeFiles\kat_kem.dir\kat_kem.c.obj tests\CMakeFiles\kat_kem.dir\test_helpers.c.obj  /out:tests\kat_kem.exe /implib:tests\kat_kem.lib /pdb:tests\kat_kem.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console   /STACK:8192000  lib\oqs.lib  lib\oqs-internal.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK Pass 1: command "C:\PROGRA~1\MIB055~1\2022\PROFES~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x64\link.exe /nologo tests\CMakeFiles\kat_kem.dir\kat_kem.c.obj tests\CMakeFiles\kat_kem.dir\test_helpers.c.obj /out:tests\kat_kem.exe /implib:tests\kat_kem.lib /pdb:tests\kat_kem.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console /STACK:8192000 lib\oqs.lib lib\oqs-internal.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:tests\CMakeFiles\kat_kem.dir/intermediate.manifest tests\CMakeFiles\kat_kem.dir/manifest.res" failed (exit code 1169) with the following output:
oqs-internal.lib(common.c.obj) : error LNK2005: OQS_CPU_has_extension already defined in oqs.lib(oqs.dll)
oqs-internal.lib(common.c.obj) : error LNK2005: OQS_init already defined in oqs.lib(oqs.dll)
oqs-internal.lib(common.c.obj) : error LNK2005: OQS_destroy already defined in oqs.lib(oqs.dll)
oqs-internal.lib(common.c.obj) : error LNK2005: OQS_MEM_secure_free already defined in oqs.lib(oqs.dll)
oqs-internal.lib(common.c.obj) : error LNK2005: OQS_MEM_insecure_free already defined in oqs.lib(oqs.dll)
   Creating library tests\kat_kem.lib and object tests\kat_kem.exp
tests\kat_kem.exe : fatal error LNK1169: one or more multiply defined symbols found
```
Looks like some APIs (OQS_CPU_has_extension ...) in both oqs.dll and import library oqs.lib and also in a static lib oqs-internal.lib. Both include common.c.obj. The static lib build probably just links to the first one found. I tried removing oqs-internal.lib or just common.obj but then get other errors.

**Environment (please complete the following information):**
 - OS: Windows 11
 - OpenSSL version n/a
 - Compiler version used : Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32538 for x64
 - Build variables used: -DBUILD_SHARED_LIBS=ON
 - liboqs version:  main branch

**Comment by baentsch** [comment]
Thanks for the bug report and initial analysis. Unfortunately, no-one in the OQS core team has serious experience with Windows and we have not heard interest in support for this OS beyond the [baseline support](https://github.com/open-quantum-safe/liboqs/blob/main/PLATFORMS.md#tier-2) we have for it. Any additional information for the utility/use case of this for you would be very welcome to help us prioritize: Thanks in advance.

**Comment by matlimatli** [comment]
I created a PR with a simple workaround, using the same technique that was already being used when cross-compiling on windows, i.e. add a linker flag for allowing multiple definitions of symbols. There seems to be some caveats to using this technique in general with the MS compilers, but for these test programs it should be OK.

**Comment by baentsch** [comment]
Thanks again @matlimatli for the fix! In absence of a CI test, @smcmahonibm can you confirm this solves the issue for you?

**Comment by smcmahonibm** [comment]
> Thanks again @matlimatli for the fix! In absence of a CI test, @smcmahonibm can you confirm this solves the issue for you?

Yes it worked thanks for the fix.

The shared library option (.dll) is an important build option for windows in my opinion.

**Comment by baentsch** [comment]
> Yes it worked thanks for the fix.

Thanks for the confirmation.

> The shared library option (.dll) is an important build option for windows in my opinion.

Then by all means, please consider contributing a PR adding this to the (github) CI suite to avoid regressions that may impact you or others again.

**Comment by democuritus** [comment]
Describe the bug
Building on Windows with shared lib (.dll) setting "-DBUILD_SHARED_LIBS=ON" fails to build oqs.dll.
To Reproduce
clone liboqs main branch

mkdir build
cd build
cmake -GNinja -DBUILD_SHARED_LIBS=ON ..
ninja
(see screenshot below)

Expected behavior
kat_kem.exe and kat_sig.exe should build OK.
The oqs.dll and all other .exe build OK.
Those test build OK with static lib only build - i.e. no "-DBUILD_SHARED_LIBS=ON".

Screenshots
ninja console output:
[0/1] cmd.exe /C "cd /D D:\liboqs-main\liboqs-main && E:\C...s/copy_from_upstream/repos --ignore=tests/test_kat_all.py"================================================= test session starts =================================================
platform win32 -- Python 3.13.0, pytest-8.3.3, pluggy-1.5.0 -- E:\python\python.exe
cachedir: .pytest_cache
rootdir: D:\liboqs-main\liboqs-main
plugins: xdist-3.6.1
16 workers [1043 items]
tests\helpers.py:43: AssertionError
------------------------------------------------ Captured stdout call -------------------------------------------------
. > D:/liboqs-main/liboqs-main\tests\test_kem.EXE FrodoKEM-640-AES

=============================================== short test summary info ===============================================
FAILED tests/test_cmdline.py::test_kem[FrodoKEM-1344-AES] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[Classic-McEliece-6960119f] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[Classic-McEliece-348864] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[FrodoKEM-976-SHAKE] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[Kyber1024] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[Classic-McEliece-8192128] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[ML-DSA-65-ipd] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[FrodoKEM-1344-AES] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[Classic-McEliece-8192128f] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[ML-KEM-512] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[ML-DSA-65] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[ML-DSA-87-ipd] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[SPHINCS+-SHA2-128f-simple] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[ML-KEM-1024] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[ML-DSA-87] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[SPHINCS+-SHA2-128s-simple] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[sntrup761] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[FrodoKEM-640-AES] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[SPHINCS+-SHA2-192f-simple] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[Falcon-512] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[Falcon-1024] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[FrodoKEM-640-SHAKE] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[Falcon-padded-512] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[FrodoKEM-976-AES] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdpg-128-small] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[MAYO-2] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdp-192-fast] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdpg-192-balanced] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdp-192-small] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[MAYO-3] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdpg-192-fast] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdp-256-balanced] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[MAYO-5] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdpg-192-small] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdp-256-fast] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdp-128-balanced] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdpg-256-balanced] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdp-128-fast] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdpg-256-small] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdp-192-balanced] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[cross-rsdpg-128-balanced] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[Dilithium2] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[Dilithium3] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[Dilithium5] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[ML-DSA-44-ipd] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[ML-DSA-44] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[SPHINCS+-SHA2-192s-simple] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[SPHINCS+-SHA2-256f-simple] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[SPHINCS+-SHA2-256s-simple] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[Kyber512] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[Kyber768] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[SPHINCS+-SHAKE-128f-simple] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[SPHINCS+-SHAKE-128s-simple] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[SPHINCS+-SHAKE-192f-simple] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[SPHINCS+-SHAKE-192s-simple] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[SPHINCS+-SHAKE-256f-simple] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[SPHINCS+-SHAKE-256s-simple] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_sig[MAYO-1] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[Classic-McEliece-460896] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[Classic-McEliece-460896f] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_mem.py::test_mem_kem[FrodoKEM-640-AES] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_mem.py::test_mem_kem[FrodoKEM-1344-AES] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_cmdline.py::test_sig[MAYO-2] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_cmdline.py::test_sig[MAYO-3] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_mem.py::test_mem_sig[MAYO-2] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_mem.py::test_mem_sig[MAYO-5] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_speed.py::test_kem[FrodoKEM-640-AES] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_speed.py::test_kem[FrodoKEM-976-AES] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_mem.py::test_mem_sig[MAYO-1] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_speed.py::test_sig[MAYO-1] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_speed.py::test_sig[MAYO-3] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_speed.py::test_sig[MAYO-2] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_kat.py::test_kem[Classic-McEliece-6960119] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_speed.py::test_sig[MAYO-5] - AssertionError: Got unexpected return code 3221225477
FAILED tests/test_cmdline.py::test_kem[FrodoKEM-640-AES] - AssertionError: Got unexpected return code 3221225477
=============================== 75 failed, 292 passed, 676 skipped in 115.46s (0:01:55) ===============================

FAILED: tests/CMakeFiles/run_tests D:/liboqs-main/liboqs-main/tests/CMakeFiles/run_tests
cmd.exe /C "cd /D D:\liboqs-main\liboqs-main && E:\Cmake\bin\cmake.exe -E env OQS_BUILD_DIR=D:/liboqs-main/liboqs-main python -m pytest --verbose --numprocesses=auto --ignore=scripts/copy_from_upstream/repos --ignore=tests/test_kat_all.py"
ninja: build stopped: subcommand failed.

Environment (please complete the following information):
OS: Windows 11
OpenSSL version n/a
Compiler version used : cmake version 3.26.0-rc1
Build variables used: -DBUILD_SHARED_LIBS=ON
liboqs version: main branch

**Comment by matlimatli** [comment]
@democuritus This should probably be written as a new issue. However, there seems to be two separate problems here. The most obvious is that when running the tests on Windows, the generated DLL is not found as it is not in the PATH. The easy workaround for this is to copy the DLL from the bin directory to the tests directory. 

The next issue seems to only occur when using Ninja as a generator. The workaround for that is to use the default Visual Studio Generator instead, which is slower, but for some reason works better. 

What works for me is:
```mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=ON ..
cmake --build .
copy bin\Debug\oqs.dll tests
cmake --build . -t run_tests```

**Comment by democuritus** [comment]
thank you very much! I found that when I complie liboqs under windows ,It seems only 32-bit dl file can be generated. and liboqs-Java seems only support 64-bit tool chain to generate jar file,so there is a problem that liboqs library can be applied at integrated Java project under windows

**Comment by democuritus** [comment]
> @democuritus This should probably be written as a new issue. However, there seems to be two separate problems here. The most obvious is that when running the tests on Windows, the generated DLL is not found as it is not in the PATH. The easy workaround for this is to copy the DLL from the bin directory to the tests directory.
> 
> The next issue seems to only occur when using Ninja as a generator. The workaround for that is to use the default Visual Studio Generator instead, which is slower, but for some reason works better.
> 
> What works for me is:
> 
> ```
> cd build
> cmake -DBUILD_SHARED_LIBS=ON ..
> cmake --build .
> copy bin\Debug\oqs.dll tests
> cmake --build . -t run_tests```
> ```



> @democuritus This should probably be written as a new issue. However, there seems to be two separate problems here. The most obvious is that when running the tests on Windows, the generated DLL is not found as it is not in the PATH. The easy workaround for this is to copy the DLL from the bin directory to the tests directory.
> 
> The next issue seems to only occur when using Ninja as a generator. The workaround for that is to use the default Visual Studio Generator instead, which is slower, but for some reason works better.
> 
> What works for me is:
> 
> ```
> cd build
> cmake -DBUILD_SHARED_LIBS=ON ..
> cmake --build .
> copy bin\Debug\oqs.dll tests
> cmake --build . -t run_tests```
> ```

**Comment by democuritus** [comment]
thank you very much！I had generated the oqs.dll using:
cmake -G "Visual Studio 17 2022" -A x64 -DBUILD_SHARED_LIBS=ON ..
cmake --build . --config Release
&nbsp; in x64 Native Tools Command Prompt of visual studio.
OS:Windows 11
visual studio version: 2022



---Original---
From: ***@***.***&gt;
Date: Tue, Oct 15, 2024 06:01 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-quantum-safe/liboqs] Windows build with"-DBUILD_SHARED_LIBS=ON" (Issue #1749)




 
@democuritus This should probably be written as a new issue. However, there seems to be two separate problems here. The most obvious is that when running the tests on Windows, the generated DLL is not found as it is not in the PATH. The easy workaround for this is to copy the DLL from the bin directory to the tests directory.
 
The next issue seems to only occur when using Ninja as a generator. The workaround for that is to use the default Visual Studio Generator instead, which is slower, but for some reason works better.
 
What works for me is:
 cd build cmake -DBUILD_SHARED_LIBS=ON .. cmake --build . copy bin\Debug\oqs.dll tests cmake --build . -t run_tests```
