### ISSUE TITLE
Using server/client instead of alice/bob in API

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/liboqs#18]
How about changing Alice and Bob to Server and Client in the public API? I find the names a bit confusing, as I always need to double-check which one plays which role.

**Comment by dstebila** [comment]
Which party plays which role depends on the protocol.  In TLS 1.2, since the server sends the first DH share, the server would play the "Alice" role in our naming.  But in TLS 1.3, since the client sends the first DH share, the client would play the "Alice" role in our naming.  Thus, I'm inclined to avoid "client"/"server".  

If "Alice" and "Bob" are too informal, there's "initiator" and "responder" following NIST's API for the PQCrypto submissions, but again the risk that "initiator" and "responder" in the network protocol may not correspond with who sends the first key share.

**Comment by christianpaquin** [comment]
Right, client/server might not be suited in all situations. I don't have a better suggestion at the moment that works across the board; I'll get used to Alice and Bob :)
