### ISSUE TITLE
Zephyr builds: revert to latest ci image once fix is available

### ISSUE THREAD

**Issue by bhess** [open-quantum-safe/liboqs#1948]
Zephyr builds in CI fail since about [a week](https://github.com/open-quantum-safe/liboqs/actions/runs/11147629806/job/30988529872), while the liboqs changes in the builds seem unrelated to zephyr.

The timing coincides with a zephyr container update https://github.com/zephyrproject-rtos/docker-image/pkgs/container/ci/282662529?tag=main-amd64.

I haven't found the root cause of the build failure, but https://github.com/zephyrproject-rtos/docker-image/issues/205 suggests there might be an issue with the SDK used in the container image and the recommendation is to downgrade to v0.26.14. Do you have any insight here @Frauschi ?

**Comment by bhess** [comment]
Workaround by downgrading to 0.26.14 proposed in PR #1949

**Comment by Frauschi** [comment]
Just looked into it. As indicated in https://github.com/zephyrproject-rtos/docker-image/issues/205, this should (hopefully) be a temporary issue. The fix is already merged in the upstream SDK repo, so only the docker image must be updated.

Your workaround in #1949 should be totally fine until the SDK container is fixed.

**Comment by bhess** [comment]
Thanks for the confirmation @Frauschi.

**Comment by bhess** [comment]
Keeping the issue open to revert #1949 once an updated container is available.

**Comment by Frauschi** [comment]
I just opened a PR (#1953) to switch back to the latest container, as there is a new container resolving the issue.
