### ISSUE TITLE
Update HQC implementation

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#2002]

**Comment by SWilson4** [comment]
This was completed with commits 95f904bcaafe4cb12cfdf029347ac3b7c795308a and cce1bfde4e52c524b087b9687020d283fbde0f24. There is no public PR (yet) because the work was done on a private fork created from a draft security advisory. I'm not completely satisfied with how this turned out (it required admin intervention to actually merge the private PR). I will be writing some details up as part of a first stab at https://github.com/open-quantum-safe/tsc/issues/60.
