### ISSUE TITLE
Change SHAKE implementation to be NIST-compliant

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#220]
New issue based on comment by @steppenwolfe65 on PR #209:
SP800-185 3.2 states if S=N=0 cSHAKE output should be SHAKE. That would require adding a branch to the code that toggles the domain code from cSHAKE(0x04) to SHAKE(0x1F), all so you can test an invalid input.. does that make sense to you? I guess the point is, just because NIST does it, doesn't mean it is correct.

**Comment by Steppenwolfe65** [comment]
I think my comment may be misunderstood here, so allow me to clarify that statement. 
If you pass a null salt *and* nonce into cSHAKE this should be considered as *undefined behavior*, it should throw an exception or return an error code, because it is invoking the function with invalid parameters. It should *not* allow processing to continue, and it should *not* revert to SHAKE, as described in SP800-38a. Reverting to SHAKE is allowing the user to execute the function with invalid input, a clear violation of secure coding practices.

There is nothing wrong with the simple cSHAKE implementation, because it is just that; not cSHAKE, but 'simple cSHAKE' a different expression of the function, and one that was included with the original Keccak submission package. Altering that as you propose, would require implementing a complete implementation of cSHAKE, one in which in most use cases the salt will be null anyways, and that will require a segmented integer counter, and if you insist on compliance, a branching statement that toggles to SHAKE.

As for NIST, I most certainly do not agree with everything they say and do.. I was against changing the state initialization constants in the original Keccak, and was against raising the input rates to make it more competitive with SHA2, and when I read one of their papers, I always try to maintain a healthy skepticism, because after all, we shouldn't blindly follow the recommendations of some standards organization, particularly one that is joined at the hip to the NSA. It is our job to question, to criticize, and when necessary, push beyond the standards.

@dstebila I think though, that you are focusing on minutia, your library has problems that are far more serious than this; there are literally thousands of secure coding standards violations, from goto statements to dangerous use of pointers. I would strongly urge you to bring the entire library up to Misra C standard, and use static analyzers to identify and correct problems.

Anyways, good luck guys..

**Comment by dstebila** [comment]
Fixed by #244
