### ISSUE TITLE
(master branch) Not possible to disable all signature schemes

### ISSUE THREAD

**Issue by himsen** [open-quantum-safe/liboqs#314]
Disabling both signature schemes result in a compilation error. To reproduce:

```
$autoreconf -i
$./configure --disable-sig-picnic --disable-sig-qtesla
$make
src/sig/test_sig.c:24:39: error: ISO C forbids empty initializer braces [-Werror=pedantic]
 struct sig_testcase sig_testcases[] = {
src/sig/test_sig.c:24:21: error: zero or negative size array ‘sig_testcases’ 
 struct sig_testcase sig_testcases[] = { 

cc1: all warnings being treated as errors
make[2]: *** [src/sig/test_sig-test_sig.o] Error 1
```

**Comment by dstebila** [comment]
This is fixed in how we handle algorithm enable/disable in the new SIG API on nist-branch, as far as I can tell (for example https://github.com/open-quantum-safe/liboqs/blob/nist-branch/src/sig/test_sig.c has no array with entries dependent on #ifdef's).  So I'm inclined to ignore this for now since it will be fixed when we switch to the files from the new API.

**Comment by himsen** [comment]
Sounds reasonable.
