### ISSUE TITLE
Question Regarding Performance Differences in Digital Signature

### ISSUE THREAD

**Issue by Nitroman605** [open-quantum-safe/liboqs#634]
I did some performance test in trying to sign and verify a some data and calculating the average signing and verifying per second. I found that Dilithium and qTesla outperforms the other by a very wide margin. Here is a sample of the signing performance with NIST level 1 security level (sign per second on the same data): 

DILITHIUM  : 3136
MQDSS : 304
picnic : 563
qTesla : 2358
SPHINCS+-SHAKE256-128f-simple : 47

My question is that is this normal as the Dilithium and qTesla are a lot faster by design than the others or these results is not correct? 
Thanks

PS: I used the golang-wrapper and the code ran on the same machine under the same condition.

**Comment by dstebila** [comment]
Yes, Dilithium and qTesla are faster by design.  You can see information about each algorithm's intended performance characteristics by reading the submissions at https://nist.gov/pqcrypto.  You can also see performance in other testing frameworks such as [SUPERCOP](https://bench.cr.yp.to/results-sign.html).
