### ISSUE TITLE
Add HQC from PQClean

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#709]

**Comment by baentsch** [comment]
https://github.com/open-quantum-safe/openssl/issues/144 lead me to looking into also this issue -- which turned up a problem someone already has dealt with for LEDA: `nistseedexpander` has been (PQClean) namespaced there but not for HQC. 

--> What's the reason for this? Why is this part of `PQClean` common, but not `liboqs` common? So, should this be fixed in PQClean or in liboqs?

**Comment by dstebila** [comment]
It's not in liboqs common since, to my knowledge, we hadn't had a need for it before. Personally I'd be inclined to not have it be part of common in PQClean, since I don't think it's a primitive most crypto libraries would be expected to expose. Seems like an oversight in PQClean that there's inconsistent treatment of that primitive in LEDAcrypt versus HQC. I'd suggest we file an issue with PQClean, see which way they resolve.

**Comment by baentsch** [comment]
Fine with me. Will you want to open that issue or shall I do it? Anyway, PR https://github.com/open-quantum-safe/openssl/pull/177 then addresses all that can be done now on issue https://github.com/open-quantum-safe/openssl/issues/144 ...
