### ISSUE TITLE
Mac Installation

### ISSUE THREAD

**Issue by ankane** [open-quantum-safe/liboqs#766]
Hey, thanks for this great library! Just wanted to let you know that Mac users can now install liboqs and its dependencies in a single command with Homebrew.

```sh
brew install liboqs
```

Ref: https://github.com/Homebrew/homebrew-core/pull/56065

**Comment by ankane** [comment]
Homebrew allows you to host your own repo, but doesn't have it's own unstable branch. However, I don't think it's typically used for discovery if that's the concern (it should be primarily be an easy way for developers to do the quickstart steps in the readme). That being said, I can ask the project to remove it if you'd prefer.

**Comment by dstebila** [comment]
I think for now we'd like to hold off on having liboqs available via brew, since we still view the code and algorithms as experimental.  Within the next year the PQ algorithm landscape should consolidate further, and we'll have higher confidence in implementations too, at which point we can revisit.
