### ISSUE TITLE
Static analysis with Codacy

### ISSUE THREAD

**Issue by tlepoint** [open-quantum-safe/liboqs#88]
[https://www.codacy.com](https://www.codacy.com) (C is a community supported language)

**Comment by dstebila** [comment]
I had another discussion with someone offline who suggested Coverity, which has a version that can be used for free with open-source projects and linked into Github and Travis-CI.  This person also offered to help us understand the initial reports since he worked with Coverity before: apparently Coverity finds a lot of stuff and it can take some effort to figure out what's the alleged bug and how to fix it.  So I was leaning to Coverity -- any particular reason you advocate Codacy?

**Comment by tlepoint** [comment]
No, coverity is fine. Thanks.
