### ISSUE TITLE
Missing CMake target_include_directory for Kyber768

### ISSUE THREAD

**Issue by jschanck** [open-quantum-safe/liboqs#899]
Upstream Kyber768_META.yml is missing a "common_dep: common_ref" line, which results in  OQS_ENABLE_KEM_kyber_768 being omitted from this if statement: https://github.com/open-quantum-safe/liboqs/blob/1256e3ba99f344f52321deaf1e2606d481ffc4f1/src/kem/kyber/CMakeLists.txt#L8-L12
If you try to build liboqs with only Kyber768 (and none of the other Kyber parameter sets), the build will fail with undefined references. 

This can be reproduced using my feat.minimal-build branch (jschanck/liboqs@4feed617).
```sh
cmake -GNinja -DOQS_MINIMAL_BUILD=ON -DOQS_KEM_DEFAULT=OQS_KEM_alg_kyber_768  ..
```

**Comment by baentsch** [comment]
Bug confirmed. Probably something for @bhess?

Side note: 

> -DOQS_MINIMAL_BUILD=ON

This is a really nice new build switch: hope you intend to do a PR for this: Fast(er) build, (comparatively) small lib, (nearly) fully functioning. Nearly: `tests/example_kem|sig` fail due to "alg hardcoding" - logical as it's an example; but probably needs to be skipped in testing if this option is set.
